# Generated by Django 5.0.4 on 2024-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0002_oradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOAPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('weborangeso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keyproso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flyboxgpso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tn1APN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('weborangetn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keyprotn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keygptn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flyboxgptn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataltetddtn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geoloctn1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keybusinesstn1', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tn2APN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('weborangetn2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keygptn2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flyboxgptn2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataltetddtn2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geoloctn2', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tn2VEPGAPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('weborangetn2vepg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keyprotn2vepg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flyboxprotn2vepg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataltetddtn2vepg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
