# Generated by Django 5.0.4 on 2024-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0004_rename_flyboxgptn2_tn2apn_keybusinesstn2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tn1apn',
            name='flyboxprotn1',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='tn2apn',
            name='flyboxprotn2',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
