# Generated by Django 5.0.4 on 2024-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0005_tn1apn_flyboxprotn1_tn2apn_flyboxprotn2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tn1apn',
            name='flyboxprotn1',
        ),
        migrations.RemoveField(
            model_name='tn2apn',
            name='flyboxprotn2',
        ),
        migrations.AddField(
            model_name='tn2vepgapn',
            name='flyboxprotn2vepg',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
