# Generated by Django 5.0.4 on 2024-08-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashApp', '0008_alter_int_date_alter_soapn_date_alter_soepg_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tn2EPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=150, unique=True)),
                ('avg16', models.IntegerField()),
                ('peak16', models.IntegerField()),
                ('avg5', models.IntegerField()),
                ('peak5', models.IntegerField()),
                ('avg6', models.IntegerField()),
                ('peak6', models.IntegerField()),
                ('avg11', models.IntegerField()),
                ('peak11', models.IntegerField()),
                ('avg12', models.IntegerField()),
                ('peak12', models.IntegerField()),
                ('avg13', models.IntegerField()),
                ('peak13', models.IntegerField()),
                ('avg15', models.IntegerField()),
                ('peak15', models.IntegerField()),
                ('avg17', models.IntegerField()),
                ('peak17', models.IntegerField()),
                ('avg18', models.IntegerField()),
                ('peak18', models.IntegerField()),
                ('avg19', models.IntegerField()),
                ('peak19', models.IntegerField()),
                ('avg2', models.IntegerField()),
                ('peak2', models.IntegerField()),
                ('avg20', models.IntegerField()),
                ('peak20', models.IntegerField()),
                ('avg3', models.IntegerField()),
                ('peak3', models.IntegerField()),
                ('avg4', models.IntegerField()),
                ('peak4', models.IntegerField()),
                ('avg8', models.IntegerField()),
                ('peak8', models.IntegerField()),
                ('avg9', models.IntegerField()),
                ('peak9', models.IntegerField()),
                ('actpdpcont', models.BigIntegerField()),
                ('acteps', models.BigIntegerField()),
                ('actsub', models.BigIntegerField()),
            ],
        ),
    ]
